{{- if .Values.hpa }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fb-submitter-api-{{ .Values.environmentName }}
  namespace: formbuilder-platform-{{ .Values.environmentName }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fb-submitter-api-{{ .Values.environmentName }}
  minReplicas: {{ .Values.hpa.api.minReplicas }}
  maxReplicas: {{ .Values.hpa.api.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.api.targetCPUUtilizationPercentage }}
{{- end }}
